/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codes;

import javax.swing.ImageIcon;

/**
 *
 * @author Supratik Rulz
 */
public class DevoloperChoose extends javax.swing.JFrame {

    /**
     * Creates new form DevoloperChoose
     */
    
    public int yMouse,xMouse;
    public DevoloperChoose() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("LOGO.PNG")).getImage());
        this.setTitle("Go-Gmailer:Developerz");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnirban = new javax.swing.JLabel();
        lblSubhabrata = new javax.swing.JLabel();
        lblSupratik = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        TitleBar = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Go Gmailer: Developers");
        setMaximumSize(new java.awt.Dimension(650, 505));
        setMinimumSize(new java.awt.Dimension(650, 505));
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(650, 505));
        getContentPane().setLayout(null);

        lblAnirban.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAnirban.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAnirbanMouseReleased(evt);
            }
        });
        getContentPane().add(lblAnirban);
        lblAnirban.setBounds(430, 180, 140, 190);

        lblSubhabrata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSubhabrata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSubhabrataMouseReleased(evt);
            }
        });
        getContentPane().add(lblSubhabrata);
        lblSubhabrata.setBounds(260, 180, 140, 190);

        lblSupratik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSupratik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSupratikMouseReleased(evt);
            }
        });
        getContentPane().add(lblSupratik);
        lblSupratik.setBounds(90, 170, 140, 200);

        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseReleased(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(588, 0, 30, 19);

        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
        });
        getContentPane().add(lblExit);
        lblExit.setBounds(620, 0, 30, 20);

        TitleBar.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        TitleBar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                TitleBarMouseDragged(evt);
            }
        });
        TitleBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TitleBarMousePressed(evt);
            }
        });
        getContentPane().add(TitleBar);
        TitleBar.setBounds(0, 0, 650, 20);

        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        getContentPane().add(lblBack);
        lblBack.setBounds(50, 440, 60, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/developer/TEAM.PNG"))); // NOI18N
        lblBackground.setMaximumSize(new java.awt.Dimension(650, 505));
        lblBackground.setMinimumSize(new java.awt.Dimension(650, 505));
        lblBackground.setPreferredSize(new java.awt.Dimension(650, 505));
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 650, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TitleBarMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_TitleBarMouseDragged

    private void TitleBarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TitleBarMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_TitleBarMousePressed

    private void lblSupratikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSupratikMouseReleased
        // TODO add your handling code here:
        dispose();
        Supratik.main(null);
    }//GEN-LAST:event_lblSupratikMouseReleased

    private void lblSubhabrataMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSubhabrataMouseReleased
        // TODO add your handling code here:
        dispose();
        Subhabrata.main(null);
        
    }//GEN-LAST:event_lblSubhabrataMouseReleased

    private void lblAnirbanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAnirbanMouseReleased
        // TODO add your handling code here:
        dispose();
        Anirban.main(null);
    }//GEN-LAST:event_lblAnirbanMouseReleased

    private void lblMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseReleased
        // TODO add your handling code here:
        this.setState(LoginMain.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseReleased

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseReleased

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        // TODO add your handling code here:
        dispose();
        LoginMain.main(null);
    }//GEN-LAST:event_lblBackMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DevoloperChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DevoloperChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DevoloperChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DevoloperChoose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DevoloperChoose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TitleBar;
    private javax.swing.JLabel lblAnirban;
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSubhabrata;
    private javax.swing.JLabel lblSupratik;
    // End of variables declaration//GEN-END:variables
}
