/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codes;

import java.awt.Color;
import java.io.File;
import java.io.IOException;
import java.io.OutputStream;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.Multipart;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Supratik Rulz
 */
public class EmailMain extends javax.swing.JFrame {

    /**
     * Creates new form EmailMain
     */
    static private String useremailid;
    static private String userpassword;
    private String attachmentPath;
    private int xx,yy;
    
    public EmailMain() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("LOGO.PNG")).getImage());
        this.setTitle("Go-Gmailer:Rulz");
        textToEmail.setBackground(new Color(0,0,0,0));
        textSubject.setBackground(new Color(0,0,0,0));
        textBody.setBackground(new Color(0,0,0,0));
        textAttachment.setBackground(new Color(0,0,0,0));
    }
    
    protected static void setUser(String uname,String upass){
        useremailid=uname;
        userpassword=upass;
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textBody = new javax.swing.JScrollPane();
        textBodyArea = new javax.swing.JTextArea();
        lblSend = new javax.swing.JLabel();
        lblSignOut = new javax.swing.JLabel();
        textSubject = new javax.swing.JTextField();
        textToEmail = new javax.swing.JTextField();
        lblAttachment = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        textAttachment = new javax.swing.JTextField();
        lblExit = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1064, 650));
        setMinimumSize(new java.awt.Dimension(1064, 650));
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(1064, 650));
        setResizable(false);
        getContentPane().setLayout(null);

        textBody.setBorder(null);

        textBodyArea.setBackground(new java.awt.Color(175, 185, 205));
        textBodyArea.setColumns(20);
        textBodyArea.setRows(5);
        textBodyArea.setOpaque(false);
        textBody.setViewportView(textBodyArea);

        getContentPane().add(textBody);
        textBody.setBounds(350, 250, 400, 190);

        lblSend.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        lblSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSendMouseReleased(evt);
            }
        });
        getContentPane().add(lblSend);
        lblSend.setBounds(510, 470, 80, 80);

        lblSignOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSignOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblSignOutMouseReleased(evt);
            }
        });
        getContentPane().add(lblSignOut);
        lblSignOut.setBounds(50, 520, 90, 90);

        textSubject.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        textSubject.setBorder(null);
        textSubject.setOpaque(false);
        getContentPane().add(textSubject);
        textSubject.setBounds(350, 150, 400, 30);

        textToEmail.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        textToEmail.setBorder(null);
        textToEmail.setOpaque(false);
        textToEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textToEmailActionPerformed(evt);
            }
        });
        getContentPane().add(textToEmail);
        textToEmail.setBounds(350, 60, 400, 30);

        lblAttachment.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAttachment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblAttachmentMouseReleased(evt);
            }
        });
        getContentPane().add(lblAttachment);
        lblAttachment.setBounds(620, 570, 30, 40);

        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseReleased(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(50, 10, 30, 20);

        textAttachment.setBorder(null);
        textAttachment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textAttachmentActionPerformed(evt);
            }
        });
        getContentPane().add(textAttachment);
        textAttachment.setBounds(670, 579, 320, 25);

        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
        });
        getContentPane().add(lblExit);
        lblExit.setBounds(20, 10, 30, 20);

        lbltitle.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lbltitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbltitleMouseDragged(evt);
            }
        });
        lbltitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbltitleMousePressed(evt);
            }
        });
        getContentPane().add(lbltitle);
        lbltitle.setBounds(0, 0, 1064, 35);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui_images/MAIN.PNG"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 1064, 650);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbltitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleMouseDragged
        // TODO add your handling code here:
        
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        int xMouse = 0;
        int yMouse = 0;
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_lbltitleMouseDragged

    private void lbltitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleMousePressed
        // TODO add your handling code here
        
        
         xx=evt.getX();
         yy=evt.getY();
    }//GEN-LAST:event_lbltitleMousePressed

    private void lblMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseReleased
        // TODO add your handling code here:
        
         this.setState(EmailMain.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseReleased

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseReleased

    private void textToEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textToEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textToEmailActionPerformed

    private void lblSendMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSendMouseReleased
        // TODO add your handling code here:
        
       // new SendEmail(useremailid, userpassword, textToEmail.getText().trim(), textSubject.getText().trim(),textBodyArea.getText().trim());
         Properties prop=new Properties();
       prop.put("mail.smtp.ssl.trust","smtp.gmail.com");
       prop.put("mail.smtp.auth",true);
       prop.put("mail.smtp.starttls.enable",true);
       prop.put("mail.smtp.host","smtp.gmail.com");
       prop.put("mail.smtp.port","587");
       
       Session session=Session.getInstance(prop, new javax.mail.Authenticator(){
           protected javax.mail.PasswordAuthentication getPasswordAuthentication(){
               return new javax.mail.PasswordAuthentication(useremailid, userpassword);
           }
       });        
       
       try{
           InternetAddress toAddress = new InternetAddress(textToEmail.getText().trim());
           Message message = new MimeMessage(session);
           message.setFrom(new InternetAddress(useremailid));
           message.addRecipient(Message.RecipientType.TO,toAddress);
           message.setSubject(textSubject.getText().trim());
          // textAttachment.setText("");
           
      //   message.setText(textBodyArea.getText().trim());
      
           
           /*******************  ADD ATTACHMENT   ******************/
           MimeBodyPart messageBodyPart = new MimeBodyPart();
           messageBodyPart.setText(textBodyArea.getText().trim());
           Multipart multipart = new MimeMultipart();
           multipart.addBodyPart(messageBodyPart);
           messageBodyPart=new MimeBodyPart();
           DataSource source = new FileDataSource(textAttachment.getText().trim());
           messageBodyPart.setDataHandler(new DataHandler(source));
           messageBodyPart.setFileName(textAttachment.getText().substring(textAttachment.getText().lastIndexOf('\\')+1));
           multipart.addBodyPart(messageBodyPart);
           String nullcheck=textAttachment.getText().trim();
           if(nullcheck.equals("")){
               message.setText(textBodyArea.getText().trim());
           }
           else{
               message.setContent(multipart);
           }
           /***********Send Message*****************/
           Transport.send(message);
           JOptionPane.showMessageDialog(null, "Message Sent", "Successful!", JOptionPane.INFORMATION_MESSAGE);
           textAttachment.setText("");
           textToEmail.setText("");
           textSubject.setText("");
           textBodyArea.setText("");
           
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, "Message Not Sent\nReason:"+e, "Unsuccessful!", JOptionPane.INFORMATION_MESSAGE);
           System.out.println(e);
       }
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_lblSendMouseReleased

    private void lblSignOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSignOutMouseReleased
        // TODO add your handling code here:
        
        dispose();
        LoginMain.main(null);
    }//GEN-LAST:event_lblSignOutMouseReleased

    private void textAttachmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textAttachmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textAttachmentActionPerformed

    private void lblAttachmentMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAttachmentMouseReleased
        // TODO add your handling code here:
        
        JFileChooser chooser=new JFileChooser();
        chooser.showOpenDialog(null);
        File f=chooser.getSelectedFile();
        String filenamepath=f.getAbsolutePath();
        textAttachment.setText("");
        textAttachment.setText(filenamepath);
        
    }//GEN-LAST:event_lblAttachmentMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAttachment;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblSend;
    private javax.swing.JLabel lblSignOut;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JTextField textAttachment;
    private javax.swing.JScrollPane textBody;
    private javax.swing.JTextArea textBodyArea;
    private javax.swing.JTextField textSubject;
    private javax.swing.JTextField textToEmail;
    // End of variables declaration//GEN-END:variables
}
