/*
 * Here comes the text of your license
 * Each line should be prefixed with  * 
 */
package codes;

import javax.swing.ImageIcon;

/**
 *
 * @author Supratik Rulz
 */
public class Subhabrata extends javax.swing.JFrame {

    /**
     * Creates new form Subhabrata
     */
    private int xx,yy;
    public Subhabrata() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("LOGO.PNG")).getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblExit = new javax.swing.JLabel();
        lblMinimize = new javax.swing.JLabel();
        lblFb = new javax.swing.JLabel();
        lblTweeter = new javax.swing.JLabel();
        lblGplus = new javax.swing.JLabel();
        lblBack = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Go Gmailer: Subhabrata Paul");
        setMaximumSize(new java.awt.Dimension(650, 505));
        setMinimumSize(new java.awt.Dimension(650, 505));
        setUndecorated(true);
        setOpacity(0.95F);
        setPreferredSize(new java.awt.Dimension(650, 505));
        getContentPane().setLayout(null);

        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblExitMouseReleased(evt);
            }
        });
        getContentPane().add(lblExit);
        lblExit.setBounds(620, 0, 30, 23);

        lblMinimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblMinimizeMouseReleased(evt);
            }
        });
        getContentPane().add(lblMinimize);
        lblMinimize.setBounds(590, 0, 25, 23);

        lblFb.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblFbMouseReleased(evt);
            }
        });
        getContentPane().add(lblFb);
        lblFb.setBounds(270, 340, 20, 30);

        lblTweeter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTweeter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblTweeterMouseReleased(evt);
            }
        });
        getContentPane().add(lblTweeter);
        lblTweeter.setBounds(300, 340, 20, 30);

        lblGplus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblGplus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblGplusMouseReleased(evt);
            }
        });
        getContentPane().add(lblGplus);
        lblGplus.setBounds(340, 340, 30, 30);

        lblBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblBackMouseReleased(evt);
            }
        });
        getContentPane().add(lblBack);
        lblBack.setBounds(60, 450, 80, 20);

        lbltitle.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        lbltitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                lbltitleMouseDragged(evt);
            }
        });
        lbltitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lbltitleMousePressed(evt);
            }
        });
        getContentPane().add(lbltitle);
        lbltitle.setBounds(0, 0, 650, 20);

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/developer/SUBHOBRATA.PNG"))); // NOI18N
        getContentPane().add(lblBackground);
        lblBackground.setBounds(0, 0, 650, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseReleased
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblExitMouseReleased

    private void lblMinimizeMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMouseReleased
        // TODO add your handling code here:

        this.setState(EmailMain.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMouseReleased

    private void lbltitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleMouseDragged
        // TODO add your handling code here:

        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        int xMouse = 0;
        int yMouse = 0;
        this.setLocation(x-xx, y-yy);
    }//GEN-LAST:event_lbltitleMouseDragged

    private void lbltitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbltitleMousePressed
        // TODO add your handling code here

        xx=evt.getX();
        yy=evt.getY();
    }//GEN-LAST:event_lbltitleMousePressed

    private void lblBackMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseReleased
        // TODO add your handling code here:
        dispose();
        DevoloperChoose.main(null);
    }//GEN-LAST:event_lblBackMouseReleased

    private void lblFbMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFbMouseReleased
        // TODO add your handling code here:
        Browser.main(null,"https://www.facebook.com/subhabrata.paul.71");
    }//GEN-LAST:event_lblFbMouseReleased

    private void lblGplusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGplusMouseReleased
        // TODO add your handling code here:
        Browser.main(null,"https://google.com/+SubhabrataPaul95");
    }//GEN-LAST:event_lblGplusMouseReleased

    private void lblTweeterMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTweeterMouseReleased
        // TODO add your handling code here:
        Browser.main(null,"https://twitter.com/drummerboy_sp");
    }//GEN-LAST:event_lblTweeterMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Subhabrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Subhabrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Subhabrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Subhabrata.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Subhabrata().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblBack;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblFb;
    private javax.swing.JLabel lblGplus;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTweeter;
    private javax.swing.JLabel lbltitle;
    // End of variables declaration//GEN-END:variables
}
